artifact_uri: file:///c:/Users/julu9/Codes/Machine-learning-projects/IrisFlower/sql/0/302ebd24fa114cabb49e408bcac600e1/artifacts
end_time: 1686681199695
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 302ebd24fa114cabb49e408bcac600e1
run_name: righteous-worm-221
run_uuid: 302ebd24fa114cabb49e408bcac600e1
source_name: ''
source_type: 4
source_version: ''
start_time: 1686681199665
status: 3
tags: []
user_id: julu9
