artifact_location: file:///c:/Users/julu9/Codes/Machine-learning-projects/IrisFlower/sql/0
creation_time: 1686681173905
experiment_id: '0'
last_update_time: 1686681173905
lifecycle_stage: active
name: Default
